import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, basename } from "node:path";
import { log } from "../logger.js";

/**
 * After wasm-pack build, generate an enhanced TypeScript wrapper
 * that integrates with @rwasm/core's createWasmLoader.
 */
export async function generateWrapper(outDir: string): Promise<void> {
  // Find the JS glue file and WASM file generated by wasm-pack
  const files = await readdir(outDir);
  const jsFile = files.find(
    (f) =>
      f.endsWith(".js") && !f.includes("snippet") && !f.startsWith("index"),
  );
  const wasmFile = files.find((f) => f.endsWith(".wasm"));

  if (!jsFile || !wasmFile) {
    log.warn(
      "Could not find wasm-pack output files. Skipping wrapper generation.",
    );
    return;
  }

  // Read package.json to get crate name
  let crateName = "wasm-module";
  try {
    const pkgContent = await readFile(join(outDir, "package.json"), "utf-8");
    const pkg = JSON.parse(pkgContent);
    crateName = pkg.name ?? crateName;
  } catch {
    // Use default name
  }

  const jsModule = jsFile.replace(/\.js$/, "");

  const wrapper = `// Auto-generated by rwasm. Do not edit manually.
// Re-run "rwasm build" to regenerate.

import { createWasmLoader } from '@cheonghakim/core';
import init, * as wasmExports from './${jsModule}.js';

export type WasmExports = typeof wasmExports;

export const wasmModule = createWasmLoader<WasmExports>({
  name: '${crateName}',
  init,
  wasmUrl: new URL('./${wasmFile}', import.meta.url),
  exports: wasmExports,
});

// Re-export all wasm-bindgen exports for direct usage
export * from './${jsModule}.js';
`;

  await writeFile(join(outDir, "index.ts"), wrapper, "utf-8");
  log.step(`Generated wrapper: ${join(outDir, "index.ts")}`);
}
